//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_WPF_InstrumentControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int Id { get; set; }
        public int FirmId { get; set; }
        public int AddressId { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Index { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
    }
}
